In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('LR').getOrCreate()

In [31]:
df = spark.read.csv('../data/walmart_stock.csv', header=True, inferSchema=True)

In [32]:
df.columns

['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Adj Close']

In [33]:
df.printSchema()

root
 |-- Date: string (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

In [9]:
df.show(5)
df.registerTempTable("data")
spark.sql("SELECT * FROM data LIMIT 5").show()

+----------+------------------+---------+---------+------------------+--------+------------------+
|      Date|              Open|     High|      Low|             Close|  Volume|         Adj Close|
+----------+------------------+---------+---------+------------------+--------+------------------+
|2012-01-03|         59.970001|61.060001|59.869999|         60.330002|12668800|52.619234999999996|
|2012-01-04|60.209998999999996|60.349998|59.470001|59.709998999999996| 9593300|         52.078475|
|2012-01-05|         59.349998|59.619999|58.369999|         59.419998|12768200|         51.825539|
|2012-01-06|         59.419998|59.450001|58.869999|              59.0| 8069400|          51.45922|
|2012-01-09|         59.029999|59.549999|58.919998|             59.18| 6679300|51.616215000000004|
+----------+------------------+---------+---------+------------------+--------+------------------+
only showing top 5 rows

+----------+------------------+---------+---------+------------------+--------+------------------+
|      Date|              Open|     High|      Low|             Close|  Volume|         Adj Close|
+----------+------------------+---------+---------+------------------+--------+------------------+
|2012-01-03|         59.970001|61.060001|59.869999|         60.330002|12668800|52.619234999999996|
|2012-01-04|60.209998999999996|60.349998|59.470001|59.709998999999996| 9593300|         52.078475|
|2012-01-05|         59.349998|59.619999|58.369999|         59.419998|12768200|         51.825539|
|2012-01-06|         59.419998|59.450001|58.869999|              59.0| 8069400|          51.45922|
|2012-01-09|         59.029999|59.549999|58.919998|             59.18| 6679300|51.616215000000004|
+----------+------------------+---------+---------+------------------+--------+------------------+

In [9]:
df.describe().toPandas()

,summary,Date,Open,High,Low,Close,Volume,Adj Close
0,count,1258,1258,1258,1258,1258,1258,1258
1,mean,None,72.35785375357709,72.83938807631165,71.9186009594594,72.38844998012726,8222093.481717011,67.23883848728146
2,stddev,None,6.76809024470826,6.768186808159218,6.744075756255496,6.756859163732991,4519780.8431556,6.722609449996857
3,min,2012-01-03,56.389998999999996,57.060001,56.299999,56.419998,2094900,50.363689
4,max,2016-12-30,90.800003,90.970001,89.25,90.470001,80898100,84.91421600000001

In [10]:
from pyspark.sql import functions as f

In [11]:
df=df.withColumn("Open", f.format_number("Open", 2))
df=df.withColumn("Low", f.format_number("Low", 2))
df=df.withColumn("High", f.format_number("High", 2))
df=df.withColumn("Adj Close", f.format_number("Adj Close", 2))
df=df.withColumn("Close", f.format_number("Close", 2))

In [12]:
df.head()

Row(Date='2012-01-03', Open='59.97', High='61.06', Low='59.87', Close='60.33', Volume=12668800, Adj Close='52.62')

In [13]:
df1=df.withColumn('HV ratio',df['High']/df['Volume'])

In [15]:
df1.select('HV Ratio').show()

+--------------------+
|            HV Ratio|
+--------------------+
|4.819714574387472E-6|
|6.290848821573389...|
|4.669413073103491E-6|
|7.367338339901356E-6|
|8.915604928660188E-6|
|8.644477581688938E-6|
| 9.35182857861003E-6|
| 8.29141562102703E-6|
|7.712211972623653E-6|
|7.071764705882352...|
|1.015495483303447...|
|6.576354146362592...|
| 5.90145296180676E-6|
|8.547679455011844E-6|
|8.420709512685392E-6|
|1.041448324825044...|
|8.316075414862431E-6|
|9.721183974042911E-6|
|8.029436027707578E-6|
|6.307432259386365E-6|
+--------------------+
only showing top 20 rows

In [22]:
#df.orderBy(df['High'].desc()).head(1)[0][0]
spark.sql('SELECT Date FROM data ORDER BY High LIMIT 1').head(1)[0][0]

'2015-11-13'

In [15]:
res=df.select(['Date','High']).groupBy('Date').max()
res.orderBy(res['max(High)'].desc()).show()

+----------+-----------------+
|      Date|        max(High)|
+----------+-----------------+
|2015-01-13|        90.970001|
|2015-01-08|90.66999799999999|
|2015-01-09|        90.389999|
|2015-01-12|        90.309998|
|2015-01-23|        89.260002|
|2015-01-26|        89.160004|
|2015-01-07|            88.68|
|2015-01-14|        88.519997|
|2015-01-27|        88.459999|
|2015-01-22|        88.400002|
|2015-01-28|        88.230003|
|2014-11-28|        88.089996|
|2015-02-06|             88.0|
|2015-01-15|        87.779999|
|2015-01-29|        87.720001|
|2015-01-20|        87.699997|
|2015-01-16|        87.459999|
|2014-12-31|        87.440002|
|2015-02-10|        87.410004|
|2015-02-05|        87.360001|
+----------+-----------------+
only showing top 20 rows

In [23]:
df.select("Close").summary("mean").show()
from pyspark.sql.functions import mean
df.select(mean(df['Close'])).show()

+-------+-----------------+
|summary|            Close|
+-------+-----------------+
|   mean|72.38844992050863|
+-------+-----------------+

+-----------------+
|       avg(Close)|
+-----------------+
|72.38844992050863|
+-----------------+

In [19]:
df.select("Volume").summary("max","min").show()

+-------+--------+
|summary|  Volume|
+-------+--------+
|    max|80898100|
|    min| 2094900|
+-------+--------+

In [34]:
df.createOrReplaceTempView('walmart')

In [26]:
spark.sql('SELECT * from walmart WHERE Close < 60').count()
df.filter(df['Close'] < 60).count()

81

In [36]:
spark.sql('SELECT * from walmart WHERE High > 80').count()*100/df.count()
df.filter(df['High'] > 80).count() / df.count() * 100

9.141494435612083

In [37]:
df.corr('High','Volume')

-0.3384326061737161

In [15]:
df.select(f.year('Date').alias('year')).collect()

[Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2012),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2013),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2014),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),
 Row(year(Date)=2015),

In [38]:
df1=df.withColumn('year',f.year(df['Date']).alias('year'))
df1=df1.withColumn('month',f.month(df['Date']).alias('month'))

In [35]:
res=df1.select(['year','High']).groupBy('year').max()
res.orderBy(res['year'].desc()).show()

+----+---------+---------+
|year|max(year)|max(High)|
+----+---------+---------+
|2016|     2016|75.190002|
|2015|     2015|90.970001|
|2014|     2014|88.089996|
|2013|     2013|81.370003|
|2012|     2012|77.599998|
+----+---------+---------+

In [39]:
res=df1.select(['month','Close']).groupBy('month').mean()
res.orderBy(res['month'].desc()).show()

+-----+----------+-----------------+
|month|avg(month)|       avg(Close)|
+-----+----------+-----------------+
|   12|      12.0|72.84792478301885|
|   11|      11.0| 72.1110893069307|
|   10|      10.0|71.57854545454543|
|    9|       9.0|72.18411785294116|
|    8|       8.0|73.02981855454546|
|    7|       7.0|74.43971943925233|
|    6|       6.0| 72.4953774245283|
|    5|       5.0|72.30971688679247|
|    4|       4.0|72.97361900952382|
|    3|       3.0|71.77794377570092|
|    2|       2.0|  71.306804443299|
|    1|       1.0|71.44801958415842|
+-----+----------+-----------------+